### PR TITLE
Catch exceptions when emitting records

### LINKED ISSUE #14: Exceptions in emit cause stall
When emit throws an exception, it looks like the thread that reads from systemd just stops. There should likely be a `rescue` in there, or, alternatively, you could set `Thread::abort_on_exception=true`. That's not the best behavior though.

### PR DESCRIPTION
**Pull request by mikekap**
So the thread emitting them doesn't die. Also kill the process if the runner thread dies for some reason.

Closes #14

### CODE REVIEW

File: lib/fluent/plugin/in_systemd.rb [hunk 1]
```diff
@@ -29,6 +29,7 @@ def start
       @running = true
       pos_writer.start
       @thread = Thread.new(&method(:run))
+      @thread.abort_on_exception = true
```
Comment (errm) [inline lib/fluent/plugin/in_systemd.rb]: My understanding is that `Thread#abort_on_exception` is a global flag.  I.e. Setting it here will cause an exception in _any_ thread to cause the program to exit... I am not sure that this is what we wan't here, And I am not sure what the expectations of other code in the fluent ecosystem wrt to this flag, It is prob not the responsiblity of a plugin to set this flag one way or another and should really fall to fluentd...

File: lib/fluent/plugin/in_systemd.rb [hunk 2]
```diff
@@ -55,7 +56,11 @@ def read_from
 
     def run
       watch do |entry|
-        router.emit(tag, entry.realtime_timestamp.to_i, formatted(entry))
+        begin
+          router.emit(tag, entry.realtime_timestamp.to_i, formatted(entry))
+        rescue => e
+          log.error("Exception emitting record: #{e}")
+        end
```
Comment (errm) [inline lib/fluent/plugin/in_systemd.rb:63]: Seems reasonable...

Were you seeing anything being thrown at this point that could be a bug, that we should look at?

**Review by errm — CHANGES_REQUESTED** [review]
Happy to merge if we drop `abort_on_exception` bit

File: lib/fluent/plugin/in_systemd.rb (hunk 1 above)
Comment (mikekap) [reply lib/fluent/plugin/in_systemd.rb]: Yep definitely agree that we shouldn't set it globally. I tried to set the thread-local flag here (http://ruby-doc.org/core-1.9.3/Thread.html#method-i-abort_on_exception) but I don't know Ruby well enough to know that I succeeded. Does that look like the right way to call the instance method rather than the class method?

File: lib/fluent/plugin/in_systemd.rb (hunk 2 above)
Comment (mikekap) [reply lib/fluent/plugin/in_systemd.rb:63]: There's definitely a bug, but it's not in this plugin. In my case the kubernetes client that the kubernetes metadata filter plugin uses sometimes throws an SSL error which isn't wrapped properly. This kills poor journald daemon thread 😔. My plan is to report it upstream once I save the exact exception.

File: lib/fluent/plugin/in_systemd.rb (hunk 1 above)
Comment (errm) [reply lib/fluent/plugin/in_systemd.rb]: So you are calling the instance method here.

As I understand the documentation, the accessor `#abort_on_exception` reports the thread local state of this flag, but the writer `#abort_on_exception=` sets this flag globally.

> When set to true, causes all threads (including the main program) to abort if an exception is raised in thr. The process will effectively exit(0)

Comment (mikekap) [reply lib/fluent/plugin/in_systemd.rb]: It looks like the docs are wrong. I just tested this via

``` ruby
#Thread.abort_on_exception = true
thread = Thread.new { sleep }
thread.abort_on_exception = true

thread2 = Thread.new { raise "Exception from thread" }
thread.join
```

If you uncomment the `Thread....` this will exit; otherwise this will hang. I opened an issue in the ruby bug tracker to fix the docs: https://bugs.ruby-lang.org/issues/12847

Comment (mikekap) [reply lib/fluent/plugin/in_systemd.rb]: Hah seems we both misread that doc. To highlight: **When set to true, causes** _all threads to abort_ **if an exception is raised in thr** - i.e. the thread that you're setting this on, not all of them.

Comment (eregon) [inline lib/fluent/plugin/in_systemd.rb]: As an external view, there is a race here, since the thread can start and the `abort_on_exception` flag is set concurrently, which means `#run` could exit silently if it happens to start executing before the flag is set. One fix would be to have instead `Thread.current.abort_on_exception = true` inside `#run` as the first statement.

Comment (mikekap) [reply lib/fluent/plugin/in_systemd.rb]: Good catch. Done.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by mikekap** [comment]
ping

**Comment by errm** [comment]
Thanks @mikekap this looks great now...thanks for the review @eregon

**Review by errm — APPROVED** [review]
